apiVersion: v1
kind: Pod
metadata:
        name: my-configmap-volume-pod
        namespace: dev
spec:
        containers:
        - name: my-app-container
          image: busybox
          command: ['sh', '-c', "echo $(cat /etc/config/player_initial_lives) && sleep 3600"]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        volumes:
        - name: config-volume
          configMap:
            name: game-demo
