apiVersion: v1
kind: Pod
metadata:
  name: secure-busybox
  namespace: dev
spec:
  containers:
  - name: secure-busybox
    image: busybox
    command: ["sh", "-c", "cat /message/message.txt && sleep 1h"]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /message
    securityContext:
      allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 2000
    runAsGroup: 3000
    fsGroup: 3000
  volumes:
  - name: sec-ctx-vol
    hostPath:
      path: /etc/message


